spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Encuestas?useSSL=false&serverTimezone=UTC
    username: vemm
    password: abc123??
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true